notifications:
  email: false

services:
  - docker

language: python
python: 2.7

addons:
  ssh_known_hosts: labcomp.edwarbaron.me

before_install:
  - pip install docker-compose

install:
  - pip install fabric

script:
  - cp env.example .env
  - docker-compose build
  - fab test:sleep=10

deploy:
  provider: script
  script: fab deploy_production
  on:
    branch: master
