version: '2'

services:

  redis:
    image: redis:latest

  ldap:
    image: osixia/openldap
    volumes:
      - ~/data/labcomp/ldap:/var/lib/ldap
    environment:
      - LDAP_ORGANISATION=Labcomp C.A
      - LDAP_DOMAIN=labcomp.com

  mysql:
    image: mysql
    volumes:
      - ~/data/labcomp/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=labcomp
      - MYSQL_USER=labcomp
      - MYSQL_PASSWORD=labcomp
      - MYSQL_ROOT_PASSWORD=labcomp

  admin-dev:
    build:
      context: .
      dockerfile: Dockerfile-Development
    env_file: ./.env
    volumes:
      - ./django:/srv/www/django
    working_dir: /srv/www/django

  admin-pro:
    build:
      context: .
      dockerfile: Dockerfile-Production
    env_file: ./.env
    volumes:
      - ./django:/srv/www/django
      - ./run:/srv/www/run
    working_dir: /srv/www/django
    restart: always

  nginx:
    build: ./compose/nginx
    env_file: ./.env
    volumes:
      - ./django/public/media/:/srv/www/public/media/
      - ./django/public/staticfiles/:/srv/www/public/staticfiles/
      - ./django/public/app/:/srv/www/public/app/
      - ./run:/srv/www/run
    restart: always
    working_dir: /var/www/run
    ports:
      - '80:80'
