version: '2'

services:

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis
    restart: always

  mysql:
    extends:
      file: docker-compose-common.yml
      service: mysql
    restart: always

  celerybeat:
    extends:
      file: docker-compose-common.yml
      service: admin-pro
    command: celery -A labcomp beat -l info --pidfile="/tmp/beat.pid"
    depends_on:
      - mysql
      - redis

  celeryworker:
    extends:
      file: docker-compose-common.yml
      service: admin-pro
    command: celery -A labcomp worker -l info --pidfile="/tmp/worker.pid"
    depends_on:
      - mysql
      - redis

  django:
    extends:
      file: docker-compose-common.yml
      service: admin-pro
    command: uwsgi --emperor uwsgi.ini
    depends_on:
      - mysql
      - redis

  nginx:
    extends:
      file: docker-compose-common.yml
      service: nginx
    ports:
      - "80:80"
